### This notebook demonstrates how to use the BattETL Transformer class.

In [1]:
import os
import pandas as pd
from battetl.extract import Extractor
from battetl.transform import Transformer

In [2]:
# Load the data with the Extractor
data_directory = os.path.join('..', '..','tests','data','maccor_cycler_data','simple_data')
data_file_path = os.path.join(data_directory,'BG_Maccor_Testdata - 079.txt')
stats_file_path = os.path.join(data_directory,'BG_Maccor_Testdata - 079 [STATS].txt')
schedule_file_paths = [os.path.join(data_directory,'BG_Maccor_Schedule.000')]
paths = [
    data_file_path,
    stats_file_path
]
extractor = Extractor()
extractor.schedule_from_files(schedule_file_paths)
extractor.data_from_files(paths)

2023-04-07 12:07:12,204 INFO [utils:24] Load environment variables from /Users/zander/Desktop/battetl/examples/submodule_demos/.env
2023-04-07 12:07:12,207 INFO [utils:28] Set logger level to DEBUG
2023-04-07 12:07:12,209 INFO [Extractor:73] Total 1 files
2023-04-07 12:07:12,209 INFO [Extractor:77] Processing procedure files for Maccor
2023-04-07 12:07:12,210 INFO [Extractor:125] Importing Maccor procedure ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Schedule.000
2023-04-07 12:07:12,216 INFO [Extractor:252] Identified Maccor procedure steps: {"chg": [2, 7, 12, 17, 22, 27, 32, 37], "dsg": [5, 10, 15, 20, 25, 30, 35], "rst": [1, 3, 6, 8, 11, 13, 16, 18, 21, 23, 26, 28, 31, 33, 36, 38]}
2023-04-07 12:07:12,217 INFO [Extractor:53] Total 2 files
2023-04-07 12:07:12,217 INFO [Extractor:574] Load file path: ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079.txt
2023-04-07 12:07:12,219 DEBUG [Extractor:579] header lines: 2
2023-04-07 12:07:12,219 DEBUG [Extractor:580] header info: {"Today''s Date": '02/27/2023 11:18:36 AM', 'Date of Tes': '03/26/2020 11:00:14 PM'}
2023-04-07 12:07:12,397 DEBUG [Extractor:598] Read 141981 rows and 14 columns from ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079.txt
2023-04-07 12:07:12,399 INFO [Extractor:604] Cycle make: maccor. Data type: test_data
2023-04-07 12:07:12,399 DEBUG [Extractor:613] Update raw_test_data_meta_data
2023-04-07 12:07:12,409 DEBUG [Extractor:627] Update raw_test_data. Total rows: 141981
2023-04-07 12:07:12,411 INFO [Extractor:574] Load file path: ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079 [STATS].txt
2023-04-07 12:07:12,412 DEBUG [Extractor:579] header lines: 8
2023-04-07 12:07:12,413 DEBUG [Extractor:580] header info: {'TesterI': 'Tester #2', 'Channel Numbe': '79', 'TestNam': 'BG_Characterization.000', 'TestDes': '                                                                \x04               ', 'StartDateTim': '43916.9585040509', 'Charge': 'Discharge'}
2023-04-07 12:07:12,416 DEBUG [Extractor:598] Read 8 rows and 20 columns from ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079 [STATS].txt
2023-04-07 12:07:12,417 INFO [Extractor:604] Cycle make: maccor. Data type: cycle_stats
2023-04-07 12:07:12,418 DEBUG [Extractor:616] Update raw_cycle_stats_meta_data
2023-04-07 12:07:12,419 DEBUG [Extractor:638] Update raw_cycle_stats. Total rows: 8
2023-04-07 12:07:12,419 INFO [Extractor:58] Extract success

In [3]:
# Transform the raw data
transformer = Transformer(timezone='America/Los_Angeles')
transformer.transform_test_data(extractor.raw_test_data)
transformer.transform_cycle_stats(extractor.raw_cycle_stats)

2023-04-07 12:07:12,443 INFO [utils:24] Load environment variables from /Users/zander/Desktop/battetl/examples/submodule_demos/.env
2023-04-07 12:07:12,446 INFO [utils:28] Set logger level to DEBUG
2023-04-07 12:07:12,448 INFO [Transformer:69] Transform test data
2023-04-07 12:07:12,458 INFO [utils:84] Drop unnamed columns
2023-04-07 12:07:12,460 INFO [utils:108] Drop column Unnamed: 13
2023-04-07 12:07:12,465 INFO [Transformer:75] Cycle make: maccor. Data type: test_data
2023-04-07 12:07:12,466 INFO [utils:188] Rename column names to BattETL format
2023-04-07 12:07:12,466 DEBUG [utils:189] Columns before renaming: ['Cyc#' 'Step' 'TestTime(s)' 'StepTime(s)' 'Capacity(Ah)' 'Watt-hr'
 'Current(A)' 'Voltage(V)' 'ES' 'DPt Time' 'ACR' 'DCIR' 'Temp 1']
2023-04-07 12:07:12,474 DEBUG [utils:213] Columns after renaming: ['cycle' 'step' 'test_time_s' 'step_time_s' 'maccor_capacity_ah'
 'maccor_energy_wh' 'current_a' 'voltage_v' 'es' 'recorded_datetime' 'acr'
 'dcir' 'thermocouple_1_c']
2023-04-07 12:07:12,475 INFO [utils:231] Convert data to milli-
2023-04-07 12:07:12,476 DEBUG [utils:234] Converting maccor_capacity_ah
2023-04-07 12:07:12,607 DEBUG [utils:239] Rename column name to maccor_capacity_mah
2023-04-07 12:07:12,616 DEBUG [utils:234] Converting maccor_energy_wh
2023-04-07 12:07:12,752 DEBUG [utils:239] Rename column name to maccor_energy_mwh
2023-04-07 12:07:12,759 DEBUG [utils:234] Converting current_a
2023-04-07 12:07:12,894 DEBUG [utils:239] Rename column name to current_ma
2023-04-07 12:07:12,902 DEBUG [utils:234] Converting voltage_v
2023-04-07 12:07:13,046 DEBUG [utils:239] Rename column name to voltage_mv
2023-04-07 12:07:13,052 INFO [Transformer:259] Convert datetime and add unixtime_s
2023-04-07 12:07:13,053 INFO [utils:314] Convert recorded_datetime to UTC with timezone America/Los_Angeles
2023-04-07 12:07:13,409 DEBUG [utils:355] Found datetime format "%m/%d/%Y %I:%M:%S %p" for column recorded_datetime
2023-04-07 12:07:13,442 INFO [Transformer:284] Convert column `cycle` to uint16
2023-04-07 12:07:13,444 INFO [utils:260] Sort DataFrame by ['unixtime_s', 'step']
2023-04-07 12:07:13,473 DEBUG [utils:264] Sorted rows: 141981
2023-04-07 12:07:13,474 INFO [Transformer:104] Transform cycle stats
2023-04-07 12:07:13,475 INFO [utils:84] Drop unnamed columns
2023-04-07 12:07:13,476 INFO [Transformer:110] cycle make: maccor, data type: cycle_stats
2023-04-07 12:07:13,477 INFO [utils:188] Rename column names to BattETL format
2023-04-07 12:07:13,478 DEBUG [utils:189] Columns before renaming: ['Cycle' 'Cycle Type' 'Test Time' 'Current' 'Voltage' 'AH-IN' 'AH-OUT'
 'WH-IN' 'WH-OUT' 'ACR' 'DCIR' 'T1_Start' 'T1_End' 'T1_Min' 'T1_Max'
 'T1_Start.1' 'T1_End.1' 'T1_Min.1' 'T1_Max.1' 'Date']
2023-04-07 12:07:13,479 DEBUG [utils:213] Columns after renaming: ['cycle' 'cycle type' 'test_time_s' 'maccor_min_current_ma'
 'maccor_min_voltage_mv' 'reported_charge_capacity_ah'
 'reported_discharge_capacity_ah' 'reported_charge_energy_wh'
 'reported_discharge_energy_wh' 'acr_ohm' 'dcir'
 'maccor_charge_thermocouple_start_c' 'maccor_charge_thermocouple_end_c'
 'maccor_charge_thermocouple_min_c' 'maccor_charge_thermocouple_max_c'
 'maccor_discharge_thermocouple_start_c'
 'maccor_discharge_thermocouple_end_c'
 'maccor_discharge_thermocouple_min_c'
 'maccor_discharge_thermocouple_max_c' 'date']
2023-04-07 12:07:13,480 INFO [utils:231] Convert data to milli-
2023-04-07 12:07:13,480 DEBUG [utils:234] Converting reported_charge_capacity_ah
2023-04-07 12:07:13,481 DEBUG [utils:239] Rename column name to reported_charge_capacity_mah
2023-04-07 12:07:13,482 DEBUG [utils:234] Converting reported_discharge_capacity_ah
2023-04-07 12:07:13,483 DEBUG [utils:239] Rename column name to reported_discharge_capacity_mah
2023-04-07 12:07:13,484 DEBUG [utils:234] Converting reported_charge_energy_wh
2023-04-07 12:07:13,485 DEBUG [utils:239] Rename column name to reported_charge_energy_mwh
2023-04-07 12:07:13,487 DEBUG [utils:234] Converting reported_discharge_energy_wh
2023-04-07 12:07:13,488 DEBUG [utils:239] Rename column name to reported_discharge_energy_mwh
2023-04-07 12:07:13,489 INFO [Transformer:284] Convert column `cycle` to uint16
2023-04-07 12:07:13,491 INFO [utils:284] Convert test_time_s to seconds
2023-04-07 12:07:13,493 INFO [utils:260] Sort DataFrame by ['cycle']
2023-04-07 12:07:13,494 DEBUG [utils:264] Sorted rows: 8

,cycle,cycle type,test_time_s,maccor_min_current_ma,maccor_min_voltage_mv,reported_charge_capacity_mah,reported_discharge_capacity_mah,reported_charge_energy_mwh,reported_discharge_energy_mwh,acr_ohm,dcir,maccor_charge_thermocouple_start_c,maccor_charge_thermocouple_end_c,maccor_charge_thermocouple_min_c,maccor_charge_thermocouple_max_c,maccor_discharge_thermocouple_start_c,maccor_discharge_thermocouple_end_c,maccor_discharge_thermocouple_min_c,maccor_discharge_thermocouple_max_c,date
0,0,NaN,539.16,0.099794,4.200122,36.577804,NaN,153.244853,NaN,0,0,26.537836,26.621141,26.537836,26.654465,NaN,NaN,NaN,NaN,43916.964748
1,1,NaN,140872.77,0.099794,4.199969,2890.785664,2903.893350,10844.128589,10684.808253,0,0,26.654465,26.587818,26.304579,26.987686,26.487854,26.887722,26.271259,26.904381,43918.588977
2,2,NaN,210878.16,0.099947,4.199969,2857.675195,2860.099388,10750.549863,10517.275027,0,0,26.637804,26.471189,26.371225,26.954365,26.554497,27.087656,26.354565,27.154297,43919.399228
3,3,NaN,246583.54,0.099794,4.199817,2833.653732,2832.018735,10713.034852,10383.109116,0,0,26.871058,26.571159,26.554497,27.170961,26.421207,27.704117,26.221273,27.704117,43919.812493
4,4,NaN,262234.69,0.099947,4.200122,2804.068778,2801.992153,10724.094741,10173.873951,0,0,27.220943,26.671124,26.654465,27.987354,26.521175,29.436874,26.504513,29.436874,43919.993650
5,5,NaN,271566.09,0.099794,4.200122,2778.967842,2778.055297,10774.286333,9936.036711,0,0,27.720778,26.521175,26.521175,31.011431,26.454531,32.686275,26.454531,32.686275,43920.101663
6,6,NaN,277930.22,0.099641,4.199969,2759.421513,2758.559727,10889.422138,9627.696107,0,0,29.770096,26.821075,26.821075,39.401909,26.487854,41.535053,26.471189,41.535053,43920.175333
7,7,NaN,283295.21,0.099947,4.199817,2743.710761,2742.484959,10964.523516,9399.777453,0,0,31.531771,26.671124,26.654465,48.155888,26.637804,51.243423,26.621141,51.243423,43920.237438

In [4]:
# Transformed cycle data:
transformer.test_data.head()

,cycle,step,test_time_s,step_time_s,maccor_capacity_mah,maccor_energy_mwh,current_ma,voltage_mv,es,recorded_datetime,acr,dcir,thermocouple_1_c,unixtime_s
0,0,1,0.00,0.00,0.0,0.0,0.00,4160.30,0,2020-03-27 06:00:14+00:00,0.0,0.0,26.55,1585288814
1,0,1,2.00,2.00,0.0,0.0,0.00,4158.16,1,2020-03-27 06:00:16+00:00,0.0,0.0,26.55,1585288816
2,0,1,4.00,4.00,0.0,0.0,0.00,4158.31,1,2020-03-27 06:00:18+00:00,0.0,0.0,26.54,1585288818
3,0,1,5.00,5.00,0.0,0.0,0.00,4158.31,129,2020-03-27 06:00:19+00:00,0.0,0.0,26.54,1585288819
4,0,2,5.01,0.01,0.0,0.0,0.46,4158.01,0,2020-03-27 06:00:20+00:00,0.0,0.0,26.54,1585288820

In [5]:
# Transformed cycle stats:
cycle_stats = transformer.cycle_stats
cycle_stats.head()

,cycle,cycle type,test_time_s,maccor_min_current_ma,maccor_min_voltage_mv,reported_charge_capacity_mah,reported_discharge_capacity_mah,reported_charge_energy_mwh,reported_discharge_energy_mwh,acr_ohm,dcir,maccor_charge_thermocouple_start_c,maccor_charge_thermocouple_end_c,maccor_charge_thermocouple_min_c,maccor_charge_thermocouple_max_c,maccor_discharge_thermocouple_start_c,maccor_discharge_thermocouple_end_c,maccor_discharge_thermocouple_min_c,maccor_discharge_thermocouple_max_c,date
0,0,NaN,539.16,0.099794,4.200122,36.577804,NaN,153.244853,NaN,0,0,26.537836,26.621141,26.537836,26.654465,NaN,NaN,NaN,NaN,43916.964748
1,1,NaN,140872.77,0.099794,4.199969,2890.785664,2903.893350,10844.128589,10684.808253,0,0,26.654465,26.587818,26.304579,26.987686,26.487854,26.887722,26.271259,26.904381,43918.588977
2,2,NaN,210878.16,0.099947,4.199969,2857.675195,2860.099388,10750.549863,10517.275027,0,0,26.637804,26.471189,26.371225,26.954365,26.554497,27.087656,26.354565,27.154297,43919.399228
3,3,NaN,246583.54,0.099794,4.199817,2833.653732,2832.018735,10713.034852,10383.109116,0,0,26.871058,26.571159,26.554497,27.170961,26.421207,27.704117,26.221273,27.704117,43919.812493
4,4,NaN,262234.69,0.099947,4.200122,2804.068778,2801.992153,10724.094741,10173.873951,0,0,27.220943,26.671124,26.654465,27.987354,26.521175,29.436874,26.504513,29.436874,43919.993650

In [6]:
# Calculate cycle stats independently
cv_voltage_thresh_mv = 4195
calced_cycle_stats = transformer.calc_cycle_stats(extractor.schedule['steps'],cv_voltage_thresh_mv)
calced_cycle_stats[['reported_charge_capacity_mah','calculated_charge_capacity_mah',
                        'calculated_cc_charge_time_s','calculated_cv_charge_time_s']].head()

2023-04-07 12:07:13,600 DEBUG [Transformer:364] Calculating cycle statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,655 DEBUG [Transformer:324] Harmonized capacity/energy values for Maccor cyclers. Modified 141981 rows and 4 columns.
2023-04-07 12:07:13,656 DEBUG [Transformer:326] Added columns: charge_capacity_mah, charge_energy_mwh, discharge_capacity_mah, discharge_energy_mwh
2023-04-07 12:07:13,684 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,686 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,687 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,692 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,693 INFO [Transformer:513] No discharge data for cycle 0
2023-04-07 12:07:13,694 INFO [Transformer:399] Unable to calculate coulombic efficiency for cycle 0
2023-04-07 12:07:13,736 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,739 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,740 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,748 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,751 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,752 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
2023-04-07 12:07:13,759 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,762 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,763 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,769 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,771 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,772 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
2023-04-07 12:07:13,779 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,781 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,782 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,788 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,790 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,791 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
2023-04-07 12:07:13,796 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,798 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,799 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,805 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,807 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,807 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
2023-04-07 12:07:13,813 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,815 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,815 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,820 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,822 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,823 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
2023-04-07 12:07:13,829 DEBUG [Transformer:436] Calculating charge statistics with cv_voltage_thresh_mv: 4195
2023-04-07 12:07:13,831 DEBUG [Transformer:547] Calculating cumulative charge capacity
2023-04-07 12:07:13,832 DEBUG [Transformer:556] Capacity column: charge_capacity_mah. Energy column: charge_energy_mwh
2023-04-07 12:07:13,837 DEBUG [Transformer:507] Calculating discharge statistics
2023-04-07 12:07:13,839 DEBUG [Transformer:547] Calculating cumulative discharge capacity
2023-04-07 12:07:13,840 DEBUG [Transformer:556] Capacity column: discharge_capacity_mah. Energy column: discharge_energy_mwh
/Users/zander/opt/anaconda3/envs/battetl/lib/python3.9/site-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)

,reported_charge_capacity_mah,calculated_charge_capacity_mah,calculated_cc_charge_time_s,calculated_cv_charge_time_s
0,36.577804,36.58,256.0,278.15
1,2890.785664,2890.79,69184.0,234.12
2,2857.675195,2857.68,33988.0,490.23
3,2833.653732,2833.65,16586.0,925.44
4,2804.068778,2804.06,6114.0,1611.90

In [7]:
'''
In addition to the default functions provided by the Transformer, you can add your own custom functions 
to perform specific transformations on your data. For example, you may want to convert seconds to minutes. 
Here's an example of how you can add a custom function to do just that:
'''
def test_time_to_min(df: pd.DataFrame) -> pd.DataFrame:
    df['test_time_min'] = df['test_time_s'] / 60
    return df

transformer = Transformer(timezone='America/Los_Angeles', user_transform_cycle_stats=test_time_to_min)
transformer.transform_cycle_stats(extractor.raw_cycle_stats)
transformer.cycle_stats[['cycle','test_time_s','test_time_min']]

2023-04-07 12:07:13,877 INFO [utils:24] Load environment variables from /Users/zander/Desktop/battetl/examples/submodule_demos/.env
2023-04-07 12:07:13,879 INFO [utils:28] Set logger level to DEBUG
2023-04-07 12:07:13,881 INFO [Transformer:46] User defined transform_cycle_stats function found
2023-04-07 12:07:13,882 INFO [Transformer:104] Transform cycle stats
2023-04-07 12:07:13,883 INFO [utils:84] Drop unnamed columns
2023-04-07 12:07:13,884 INFO [Transformer:110] cycle make: maccor, data type: cycle_stats
2023-04-07 12:07:13,884 INFO [utils:188] Rename column names to BattETL format
2023-04-07 12:07:13,885 DEBUG [utils:189] Columns before renaming: ['Cycle' 'Cycle Type' 'Test Time' 'Current' 'Voltage' 'AH-IN' 'AH-OUT'
 'WH-IN' 'WH-OUT' 'ACR' 'DCIR' 'T1_Start' 'T1_End' 'T1_Min' 'T1_Max'
 'T1_Start.1' 'T1_End.1' 'T1_Min.1' 'T1_Max.1' 'Date']
2023-04-07 12:07:13,887 DEBUG [utils:213] Columns after renaming: ['cycle' 'cycle type' 'test_time_s' 'maccor_min_current_ma'
 'maccor_min_voltage_mv' 'reported_charge_capacity_ah'
 'reported_discharge_capacity_ah' 'reported_charge_energy_wh'
 'reported_discharge_energy_wh' 'acr_ohm' 'dcir'
 'maccor_charge_thermocouple_start_c' 'maccor_charge_thermocouple_end_c'
 'maccor_charge_thermocouple_min_c' 'maccor_charge_thermocouple_max_c'
 'maccor_discharge_thermocouple_start_c'
 'maccor_discharge_thermocouple_end_c'
 'maccor_discharge_thermocouple_min_c'
 'maccor_discharge_thermocouple_max_c' 'date']
2023-04-07 12:07:13,888 INFO [utils:231] Convert data to milli-
2023-04-07 12:07:13,889 DEBUG [utils:234] Converting reported_charge_capacity_ah
2023-04-07 12:07:13,890 DEBUG [utils:239] Rename column name to reported_charge_capacity_mah
2023-04-07 12:07:13,892 DEBUG [utils:234] Converting reported_discharge_capacity_ah
2023-04-07 12:07:13,894 DEBUG [utils:239] Rename column name to reported_discharge_capacity_mah
2023-04-07 12:07:13,896 DEBUG [utils:234] Converting reported_charge_energy_wh
2023-04-07 12:07:13,897 DEBUG [utils:239] Rename column name to reported_charge_energy_mwh
2023-04-07 12:07:13,899 DEBUG [utils:234] Converting reported_discharge_energy_wh
2023-04-07 12:07:13,900 DEBUG [utils:239] Rename column name to reported_discharge_energy_mwh
2023-04-07 12:07:13,902 INFO [Transformer:284] Convert column `cycle` to uint16
2023-04-07 12:07:13,902 INFO [utils:284] Convert test_time_s to seconds
2023-04-07 12:07:13,904 INFO [utils:260] Sort DataFrame by ['cycle']
2023-04-07 12:07:13,906 DEBUG [utils:264] Sorted rows: 8

   cycle  test_time_s  test_time_min
0      0       539.16       8.986000
1      1    140872.77    2347.879500
2      2    210878.16    3514.636000
3      3    246583.54    4109.725667
4      4    262234.69    4370.578167
5      5    271566.09    4526.101500
6      6    277930.22    4632.170333
7      7    283295.21    4721.586833

In [8]:
'''
By adding the custom function `test_time_to_min` to the `Transformer` object, you can now call it when you 
transform your cycle stats data. This is just one example of how you can extend the functionality of the 
Transformer to suit your needs. With this interface, you can easily transform your battery test data to the
BattETL schema and perform any additional transformations you need to prepare your data for analysis.

If you want to chain multiple custom transforms, you can create a pipeline of 
functions using the `compose` function from the `toolz` library:
'''
from toolz import compose

def test_time_to_min(df: pd.DataFrame) -> pd.DataFrame:
    df['test_time_min'] = df['test_time_s'] / 60
    return df

def test_time_to_hour(df: pd.DataFrame) -> pd.DataFrame:
    df['test_time_hour'] = df['test_time_s'] / 3600
    return df

# create pipeline of functions
pipeline = compose(test_time_to_min, test_time_to_hour)

# pass pipeline to Transformer constructor
transformer = Transformer(timezone='America/Los_Angeles', user_transform_cycle_stats=pipeline)
transformer.transform_cycle_stats(extractor.raw_cycle_stats)
transformer.cycle_stats[['cycle','test_time_s','test_time_min','test_time_hour']]

2023-04-07 12:07:13,945 INFO [utils:24] Load environment variables from /Users/zander/Desktop/battetl/examples/submodule_demos/.env
2023-04-07 12:07:13,947 INFO [utils:28] Set logger level to DEBUG
2023-04-07 12:07:13,948 INFO [Transformer:46] User defined transform_cycle_stats function found
2023-04-07 12:07:13,949 INFO [Transformer:104] Transform cycle stats
2023-04-07 12:07:13,950 INFO [utils:84] Drop unnamed columns
2023-04-07 12:07:13,951 INFO [Transformer:110] cycle make: maccor, data type: cycle_stats
2023-04-07 12:07:13,951 INFO [utils:188] Rename column names to BattETL format
2023-04-07 12:07:13,952 DEBUG [utils:189] Columns before renaming: ['Cycle' 'Cycle Type' 'Test Time' 'Current' 'Voltage' 'AH-IN' 'AH-OUT'
 'WH-IN' 'WH-OUT' 'ACR' 'DCIR' 'T1_Start' 'T1_End' 'T1_Min' 'T1_Max'
 'T1_Start.1' 'T1_End.1' 'T1_Min.1' 'T1_Max.1' 'Date']
2023-04-07 12:07:13,953 DEBUG [utils:213] Columns after renaming: ['cycle' 'cycle type' 'test_time_s' 'maccor_min_current_ma'
 'maccor_min_voltage_mv' 'reported_charge_capacity_ah'
 'reported_discharge_capacity_ah' 'reported_charge_energy_wh'
 'reported_discharge_energy_wh' 'acr_ohm' 'dcir'
 'maccor_charge_thermocouple_start_c' 'maccor_charge_thermocouple_end_c'
 'maccor_charge_thermocouple_min_c' 'maccor_charge_thermocouple_max_c'
 'maccor_discharge_thermocouple_start_c'
 'maccor_discharge_thermocouple_end_c'
 'maccor_discharge_thermocouple_min_c'
 'maccor_discharge_thermocouple_max_c' 'date']
2023-04-07 12:07:13,954 INFO [utils:231] Convert data to milli-
2023-04-07 12:07:13,955 DEBUG [utils:234] Converting reported_charge_capacity_ah
2023-04-07 12:07:13,956 DEBUG [utils:239] Rename column name to reported_charge_capacity_mah
2023-04-07 12:07:13,957 DEBUG [utils:234] Converting reported_discharge_capacity_ah
2023-04-07 12:07:13,958 DEBUG [utils:239] Rename column name to reported_discharge_capacity_mah
2023-04-07 12:07:13,959 DEBUG [utils:234] Converting reported_charge_energy_wh
2023-04-07 12:07:13,960 DEBUG [utils:239] Rename column name to reported_charge_energy_mwh
2023-04-07 12:07:13,961 DEBUG [utils:234] Converting reported_discharge_energy_wh
2023-04-07 12:07:13,962 DEBUG [utils:239] Rename column name to reported_discharge_energy_mwh
2023-04-07 12:07:13,963 INFO [Transformer:284] Convert column `cycle` to uint16
2023-04-07 12:07:13,964 INFO [utils:284] Convert test_time_s to seconds
2023-04-07 12:07:13,965 INFO [utils:260] Sort DataFrame by ['cycle']
2023-04-07 12:07:13,966 DEBUG [utils:264] Sorted rows: 8

   cycle  test_time_s  test_time_min  test_time_hour
0      0       539.16       8.986000        0.149767
1      1    140872.77    2347.879500       39.131325
2      2    210878.16    3514.636000       58.577267
3      3    246583.54    4109.725667       68.495428
4      4    262234.69    4370.578167       72.842969
5      5    271566.09    4526.101500       75.435025
6      6    277930.22    4632.170333       77.202839
7      7    283295.21    4721.586833       78.693114