This notebook demonstrates how to use the BattETL Extractor class.

In [1]:
import os
from battetl.extract import Extractor

In [2]:
# Define the paths to the raw data file or files. Note the 
data_directory = os.path.join('..', '..','tests','data','maccor_cycler_data','simple_data')
data_file_path = os.path.join(data_directory,'BG_Maccor_Testdata - 079.txt')
stats_file_path = os.path.join(data_directory,'BG_Maccor_Testdata - 079 [STATS].txt')

paths = [
    data_file_path,
    stats_file_path
]

In [3]:
# Initialize and extract data
extractor = Extractor()
extractor.data_from_files(paths)

2023-04-07 10:56:40,447 INFO [utils:24] Load environment variables from /Users/zander/Desktop/battetl/examples/submodule_examples/.env
2023-04-07 10:56:40,449 INFO [utils:28] Set logger level to DEBUG
2023-04-07 10:56:40,451 INFO [Extractor:53] Total 2 files
2023-04-07 10:56:40,452 INFO [Extractor:574] Load file path: ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079.txt
2023-04-07 10:56:40,453 DEBUG [Extractor:579] header lines: 2
2023-04-07 10:56:40,453 DEBUG [Extractor:580] header info: {"Today''s Date": '02/27/2023 11:18:36 AM', 'Date of Tes': '03/26/2020 11:00:14 PM'}
2023-04-07 10:56:40,617 DEBUG [Extractor:598] Read 141981 rows and 14 columns from ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079.txt
2023-04-07 10:56:40,619 INFO [Extractor:604] Cycle make: maccor. Data type: test_data
2023-04-07 10:56:40,619 DEBUG [Extractor:613] Update raw_test_data_meta_data
2023-04-07 10:56:40,623 DEBUG [Extractor:627] Update raw_test_data. Total rows: 141981
2023-04-07 10:56:40,624 INFO [Extractor:574] Load file path: ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079 [STATS].txt
2023-04-07 10:56:40,625 DEBUG [Extractor:579] header lines: 8
2023-04-07 10:56:40,625 DEBUG [Extractor:580] header info: {'TesterI': 'Tester #2', 'Channel Numbe': '79', 'TestNam': 'BG_Characterization.000', 'TestDes': '                                                                \x04               ', 'StartDateTim': '43916.9585040509', 'Charge': 'Discharge'}
2023-04-07 10:56:40,628 DEBUG [Extractor:598] Read 8 rows and 20 columns from ../../tests/data/maccor_cycler_data/simple_data/BG_Maccor_Testdata - 079 [STATS].txt
2023-04-07 10:56:40,629 INFO [Extractor:604] Cycle make: maccor. Data type: cycle_stats
2023-04-07 10:56:40,629 DEBUG [Extractor:616] Update raw_cycle_stats_meta_data
2023-04-07 10:56:40,630 DEBUG [Extractor:638] Update raw_cycle_stats. Total rows: 8
2023-04-07 10:56:40,631 INFO [Extractor:58] Extract success

In [4]:
# Raw test data:
extractor.raw_test_data.head()

,Cyc#,Step,TestTime(s),StepTime(s),Capacity(Ah),Watt-hr,Current(A),Voltage(V),ES,DPt Time,ACR,DCIR,Temp 1,Unnamed: 13
0,0,1,0.00,0.00,0.0,0.0,0.00000,4.16030,0,03/26/2020 11:00:14 PM,0.0,0.0,26.55,NaN
1,0,1,2.00,2.00,0.0,0.0,0.00000,4.15816,1,03/26/2020 11:00:16 PM,0.0,0.0,26.55,NaN
2,0,1,4.00,4.00,0.0,0.0,0.00000,4.15831,1,03/26/2020 11:00:18 PM,0.0,0.0,26.54,NaN
3,0,1,5.00,5.00,0.0,0.0,0.00000,4.15831,129,03/26/2020 11:00:19 PM,0.0,0.0,26.54,NaN
4,0,2,5.01,0.01,0.0,0.0,0.00046,4.15801,0,03/26/2020 11:00:20 PM,0.0,0.0,26.54,NaN

In [5]:
# Raw cycle stats:
extractor.raw_cycle_stats.head()

,Cycle,Cycle Type,Test Time,Current,Voltage,AH-IN,AH-OUT,WH-IN,WH-OUT,ACR,DCIR,T1_Start,T1_End,T1_Min,T1_Max,T1_Start.1,T1_End.1,T1_Min.1,T1_Max.1,Date
0,0,NaN,0d 00:08:59.16,0.099794,4.200122,0.036578,NaN,0.153245,NaN,0,0,26.537836,26.621141,26.537836,26.654465,NaN,NaN,NaN,NaN,43916.964748
1,1,NaN,1d 15:07:52.77,0.099794,4.199969,2.890786,2.903893,10.844129,10.684808,0,0,26.654465,26.587818,26.304579,26.987686,26.487854,26.887722,26.271259,26.904381,43918.588977
2,2,NaN,2d 10:34:38.16,0.099947,4.199969,2.857675,2.860099,10.750550,10.517275,0,0,26.637804,26.471189,26.371225,26.954365,26.554497,27.087656,26.354565,27.154297,43919.399228
3,3,NaN,2d 20:29:43.54,0.099794,4.199817,2.833654,2.832019,10.713035,10.383109,0,0,26.871058,26.571159,26.554497,27.170961,26.421207,27.704117,26.221273,27.704117,43919.812493
4,4,NaN,3d 00:50:34.69,0.099947,4.200122,2.804069,2.801992,10.724095,10.173874,0,0,27.220943,26.671124,26.654465,27.987354,26.521175,29.436874,26.504513,29.436874,43919.993650